SELECT 
    ID,
    CASE 
        WHEN QUARTILE = 1 THEN 'CRITICAL'
        WHEN QUARTILE = 2 THEN 'HIGH'
        WHEN QUARTILE = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT 
        ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS QUARTILE
    FROM 
        ECOLI_DATA
) AS SUB
ORDER BY 
    ID ASC;